project_id = "dnpakncqtzjdtkwcjpsw"

[functions.lexia-chat]
verify_jwt = false

[functions.deadline-notifications]
verify_jwt = false

[functions.org-invites]
verify_jwt = false

[functions.task-notifications]
verify_jwt = false

[functions.manage-member]
verify_jwt = false

[functions.generate-legal-piece]
verify_jwt = false

[functions.invoice-notifications]
verify_jwt = false

[functions.pagseguro-charge]
verify_jwt = false

[functions.pagseguro-webhook]
verify_jwt = false

[functions.notify-client-invoice]
verify_jwt = false

[functions.send-signed-contract]
verify_jwt = false

[functions.movement-notifications]
verify_jwt = false
