import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useOrganization } from "@/hooks/useOrganization";

// All permission codes in the system
export type Permission =
  | "MANAGE_ORGANIZATION"
  | "MANAGE_USERS"
  | "VIEW_USERS"
  | "MANAGE_PROCESSES"
  | "VIEW_PROCESSES"
  | "MANAGE_DOCUMENTS"
  | "VIEW_DOCUMENTS"
  | "MANAGE_TASKS"
  | "VIEW_TASKS"
  | "MANAGE_CLIENTS"
  | "VIEW_CLIENTS"
  | "USE_IA_ADVANCED"
  | "USE_IA_BASIC"
  | "MANAGE_AUTOMATIONS"
  | "VIEW_AUTOMATIONS"
  | "MANAGE_AGENTS"
  | "USE_AGENTS"
  | "VIEW_FINANCIAL"
  | "MANAGE_FINANCIAL"
  | "VIEW_AUDIT_LOGS"
  | "ACCESS_CLIENT_PORTAL"
  | "DELETE_ORGANIZATION"
  | "MANAGE_HEARINGS"
  | "VIEW_HEARINGS"
  | "MANAGE_LEGAL_REFS"
  | "VIEW_LEGAL_REFS"
  | "MANAGE_CONTRACTS"
  | "VIEW_CONTRACTS"
  | "MANAGE_TEAMS"
  | "VIEW_TEAMS"
  | "VIEW_METRICS"
  | "MANAGE_AGENDA"
  | "VIEW_AGENDA"
  | "SEND_EXTERNAL_MESSAGES"
  | "VIEW_EXTERNAL_MESSAGES"
  | "MANAGE_AI_TEMPLATES"
  | "VIEW_AI_TEMPLATES"
  | "GENERATE_REPORTS"
  | "VIEW_REPORTS"
  | "MANAGE_ACL"
  | "VIEW_ACL"
  | "MANAGE_COMPLIANCE"
  | "VIEW_COMPLIANCE"
  | "MANAGE_INTEGRATIONS"
  | "VIEW_INTEGRATIONS"
  | "MANAGE_NOTIFICATION_RULES"
  | "VIEW_NOTIFICATION_RULES"
  | "VIEW_PREDICTIONS"
  | "GENERATE_PREDICTIONS"
  | "MANAGE_WORKFLOWS"
  | "VIEW_WORKFLOWS"
  | "EXECUTE_WORKFLOWS"
  | "MANAGE_TICKETS"
  | "VIEW_TICKETS"
  | "CREATE_TICKETS"
  | "MANAGE_WIKI"
  | "VIEW_WIKI"
  | "MANAGE_SLA"
  | "VIEW_SLA"
  | "VIEW_AUDIT_ADVANCED"
  | "MANAGE_RISKS"
  | "VIEW_RISKS"
  | "MANAGE_SIGNATURES"
  | "VIEW_SIGNATURES"
  | "VIEW_FINANCIAL_REPORTS"
  | "GENERATE_FINANCIAL_REPORTS"
  | "MANAGE_COMMUNICATION_TEMPLATES"
  | "VIEW_COMMUNICATION_TEMPLATES"
  | "MANAGE_SECRETS"
  | "VIEW_SECRETS"
  | "MANAGE_AI_REPORTS"
  | "VIEW_AI_REPORTS"
  | "GENERATE_AI_REPORTS"
  | "MANAGE_SECURITY_LOGS"
  | "VIEW_SECURITY_LOGS"
  | "MANAGE_OKRS"
  | "VIEW_OKRS"
  | "MANAGE_GOVERNANCE"
  | "VIEW_GOVERNANCE"
  | "MANAGE_VAULT"
  | "VIEW_VAULT"
  | "MANAGE_ASSETS"
  | "VIEW_ASSETS"
  | "MANAGE_VENDORS"
  | "VIEW_VENDORS"
  | "MANAGE_CHATBOTS"
  | "USE_CHATBOT"
  | "VIEW_COURT_MONITORING"
  | "MANAGE_COURT_MONITORING"
  | "VIEW_LEGISLATIVE_UPDATES"
  | "MANAGE_LEGISLATIVE_UPDATES"
  | "VIEW_REGULATORY"
  | "MANAGE_REGULATORY";

export type OrgRole = "owner" | "admin" | "user" | "intern" | "client";

const ROLE_PERMISSIONS: Record<OrgRole, Permission[]> = {
  owner: [
    "MANAGE_ORGANIZATION", "DELETE_ORGANIZATION",
    "MANAGE_USERS", "VIEW_USERS",
    "MANAGE_PROCESSES", "VIEW_PROCESSES",
    "MANAGE_DOCUMENTS", "VIEW_DOCUMENTS",
    "MANAGE_TASKS", "VIEW_TASKS",
    "MANAGE_CLIENTS", "VIEW_CLIENTS",
    "USE_IA_ADVANCED", "USE_IA_BASIC",
    "MANAGE_AUTOMATIONS", "VIEW_AUTOMATIONS",
    "MANAGE_AGENTS", "USE_AGENTS",
    "VIEW_FINANCIAL", "MANAGE_FINANCIAL",
    "VIEW_AUDIT_LOGS", "ACCESS_CLIENT_PORTAL",
    "MANAGE_HEARINGS", "VIEW_HEARINGS",
    "MANAGE_LEGAL_REFS", "VIEW_LEGAL_REFS",
    "MANAGE_CONTRACTS", "VIEW_CONTRACTS",
    "MANAGE_TEAMS", "VIEW_TEAMS",
    "VIEW_METRICS",
    "MANAGE_AGENDA", "VIEW_AGENDA",
    "SEND_EXTERNAL_MESSAGES", "VIEW_EXTERNAL_MESSAGES",
    "MANAGE_AI_TEMPLATES", "VIEW_AI_TEMPLATES",
    "GENERATE_REPORTS", "VIEW_REPORTS",
    "MANAGE_ACL", "VIEW_ACL",
    "MANAGE_COMPLIANCE", "VIEW_COMPLIANCE",
    "MANAGE_INTEGRATIONS", "VIEW_INTEGRATIONS",
    "MANAGE_NOTIFICATION_RULES", "VIEW_NOTIFICATION_RULES",
    "VIEW_PREDICTIONS", "GENERATE_PREDICTIONS",
    "MANAGE_WORKFLOWS", "VIEW_WORKFLOWS", "EXECUTE_WORKFLOWS",
    "MANAGE_TICKETS", "VIEW_TICKETS", "CREATE_TICKETS",
    "MANAGE_WIKI", "VIEW_WIKI",
    "MANAGE_SLA", "VIEW_SLA",
    "VIEW_AUDIT_ADVANCED",
    "MANAGE_RISKS", "VIEW_RISKS",
    "MANAGE_SIGNATURES", "VIEW_SIGNATURES",
    "VIEW_FINANCIAL_REPORTS", "GENERATE_FINANCIAL_REPORTS",
    "MANAGE_COMMUNICATION_TEMPLATES", "VIEW_COMMUNICATION_TEMPLATES",
    "MANAGE_SECRETS", "VIEW_SECRETS",
    "MANAGE_AI_REPORTS", "VIEW_AI_REPORTS", "GENERATE_AI_REPORTS",
    "MANAGE_SECURITY_LOGS", "VIEW_SECURITY_LOGS",
    "MANAGE_OKRS", "VIEW_OKRS",
    "MANAGE_GOVERNANCE", "VIEW_GOVERNANCE",
    "MANAGE_VAULT", "VIEW_VAULT",
    "MANAGE_ASSETS", "VIEW_ASSETS",
    "MANAGE_VENDORS", "VIEW_VENDORS",
    "MANAGE_CHATBOTS", "USE_CHATBOT",
    "VIEW_COURT_MONITORING", "MANAGE_COURT_MONITORING",
    "VIEW_LEGISLATIVE_UPDATES", "MANAGE_LEGISLATIVE_UPDATES",
    "VIEW_REGULATORY", "MANAGE_REGULATORY",
  ],
  admin: [
    "MANAGE_USERS", "VIEW_USERS",
    "MANAGE_PROCESSES", "VIEW_PROCESSES",
    "MANAGE_DOCUMENTS", "VIEW_DOCUMENTS",
    "MANAGE_TASKS", "VIEW_TASKS",
    "MANAGE_CLIENTS", "VIEW_CLIENTS",
    "USE_IA_ADVANCED", "USE_IA_BASIC",
    "MANAGE_AUTOMATIONS", "VIEW_AUTOMATIONS",
    "MANAGE_AGENTS", "USE_AGENTS",
    "VIEW_FINANCIAL", "MANAGE_FINANCIAL",
    "VIEW_AUDIT_LOGS", "ACCESS_CLIENT_PORTAL",
    "MANAGE_HEARINGS", "VIEW_HEARINGS",
    "MANAGE_LEGAL_REFS", "VIEW_LEGAL_REFS",
    "MANAGE_CONTRACTS", "VIEW_CONTRACTS",
    "MANAGE_TEAMS", "VIEW_TEAMS",
    "VIEW_METRICS",
    "MANAGE_AGENDA", "VIEW_AGENDA",
    "SEND_EXTERNAL_MESSAGES", "VIEW_EXTERNAL_MESSAGES",
    "MANAGE_AI_TEMPLATES", "VIEW_AI_TEMPLATES",
    "GENERATE_REPORTS", "VIEW_REPORTS",
    "MANAGE_ACL", "VIEW_ACL",
    "MANAGE_COMPLIANCE", "VIEW_COMPLIANCE",
    "MANAGE_INTEGRATIONS", "VIEW_INTEGRATIONS",
    "MANAGE_NOTIFICATION_RULES", "VIEW_NOTIFICATION_RULES",
    "VIEW_PREDICTIONS", "GENERATE_PREDICTIONS",
    "MANAGE_WORKFLOWS", "VIEW_WORKFLOWS", "EXECUTE_WORKFLOWS",
    "MANAGE_TICKETS", "VIEW_TICKETS", "CREATE_TICKETS",
    "MANAGE_WIKI", "VIEW_WIKI",
    "MANAGE_SLA", "VIEW_SLA",
    "VIEW_AUDIT_ADVANCED",
    "MANAGE_RISKS", "VIEW_RISKS",
    "MANAGE_SIGNATURES", "VIEW_SIGNATURES",
    "VIEW_FINANCIAL_REPORTS", "GENERATE_FINANCIAL_REPORTS",
    "MANAGE_COMMUNICATION_TEMPLATES", "VIEW_COMMUNICATION_TEMPLATES",
    "MANAGE_SECRETS", "VIEW_SECRETS",
    "MANAGE_AI_REPORTS", "VIEW_AI_REPORTS", "GENERATE_AI_REPORTS",
    "MANAGE_SECURITY_LOGS", "VIEW_SECURITY_LOGS",
    "MANAGE_OKRS", "VIEW_OKRS",
    "MANAGE_GOVERNANCE", "VIEW_GOVERNANCE",
    "MANAGE_VAULT", "VIEW_VAULT",
    "MANAGE_ASSETS", "VIEW_ASSETS",
    "MANAGE_VENDORS", "VIEW_VENDORS",
    "MANAGE_CHATBOTS", "USE_CHATBOT",
  ],
  user: [
    "MANAGE_PROCESSES", "VIEW_PROCESSES",
    "MANAGE_DOCUMENTS", "VIEW_DOCUMENTS",
    "MANAGE_TASKS", "VIEW_TASKS",
    "MANAGE_CLIENTS", "VIEW_CLIENTS",
    "USE_IA_ADVANCED", "USE_IA_BASIC",
    "USE_AGENTS",
    "ACCESS_CLIENT_PORTAL",
    "MANAGE_HEARINGS", "VIEW_HEARINGS",
    "MANAGE_LEGAL_REFS", "VIEW_LEGAL_REFS",
    "MANAGE_CONTRACTS", "VIEW_CONTRACTS",
    "VIEW_TEAMS",
    "VIEW_METRICS",
    "MANAGE_AGENDA", "VIEW_AGENDA",
    "SEND_EXTERNAL_MESSAGES", "VIEW_EXTERNAL_MESSAGES",
    "VIEW_AI_TEMPLATES",
    "GENERATE_REPORTS", "VIEW_REPORTS",
    "VIEW_PREDICTIONS", "GENERATE_PREDICTIONS",
    "VIEW_NOTIFICATION_RULES",
    "VIEW_WORKFLOWS", "EXECUTE_WORKFLOWS",
    "VIEW_TICKETS", "CREATE_TICKETS",
    "MANAGE_WIKI", "VIEW_WIKI",
    "VIEW_SLA",
    "VIEW_RISKS",
    "MANAGE_SIGNATURES", "VIEW_SIGNATURES",
    "VIEW_FINANCIAL_REPORTS", "GENERATE_FINANCIAL_REPORTS",
    "VIEW_COMMUNICATION_TEMPLATES",
    "VIEW_AI_REPORTS",
    "VIEW_OKRS",
    "VIEW_GOVERNANCE",
    "VIEW_ASSETS",
    "VIEW_VENDORS",
    "USE_CHATBOT",
  ],
  intern: [
    "VIEW_PROCESSES",
    "VIEW_DOCUMENTS",
    "MANAGE_TASKS", "VIEW_TASKS",
    "VIEW_CLIENTS",
    "USE_IA_BASIC",
    "ACCESS_CLIENT_PORTAL",
    "VIEW_HEARINGS",
    "VIEW_LEGAL_REFS",
    "VIEW_CONTRACTS",
    "VIEW_TEAMS",
    "VIEW_METRICS",
    "VIEW_AGENDA",
    "VIEW_EXTERNAL_MESSAGES",
    "VIEW_AI_TEMPLATES",
    "VIEW_REPORTS",
    "VIEW_COMPLIANCE",
    "VIEW_PREDICTIONS",
    "VIEW_WORKFLOWS", "EXECUTE_WORKFLOWS",
    "VIEW_TICKETS", "CREATE_TICKETS",
    "VIEW_WIKI",
    "VIEW_SLA",
    "VIEW_SIGNATURES",
    "VIEW_AI_REPORTS",
    "VIEW_OKRS",
    "VIEW_GOVERNANCE",
    "VIEW_ASSETS",
    "USE_CHATBOT",
  ],
  client: [
    "VIEW_PROCESSES",
    "VIEW_DOCUMENTS",
    "ACCESS_CLIENT_PORTAL",
    "VIEW_HEARINGS",
    "VIEW_CONTRACTS",
    "VIEW_AGENDA",
    "CREATE_TICKETS", "VIEW_TICKETS",
    "USE_CHATBOT",
  ],
};

export const ROLE_LABELS: Record<OrgRole, string> = {
  owner: "Owner",
  admin: "Administrador",
  user: "Advogado",
  intern: "Estagiário",
  client: "Cliente",
};

export const ROLE_BADGE_VARIANT: Record<OrgRole, string> = {
  owner: "destructive",
  admin: "destructive",
  user: "default",
  intern: "warning",
  client: "secondary",
};

export function getPermissionsForRole(role: OrgRole): Permission[] {
  return ROLE_PERMISSIONS[role] || [];
}

export function roleHasPermission(role: OrgRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export const usePermissions = () => {
  const { user } = useAuth();
  const { activeOrgId } = useOrganization();

  const { data: orgRole, isLoading } = useQuery({
    queryKey: ["org-role", user?.id, activeOrgId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("user_organizations")
        .select("role")
        .eq("user_id", user!.id)
        .eq("organization_id", activeOrgId!)
        .maybeSingle();
      if (error) throw error;
      return (data?.role as OrgRole) || "user";
    },
    enabled: !!user && !!activeOrgId,
  });

  const role: OrgRole = orgRole || "user";
  const permissions = getPermissionsForRole(role);

  const hasPermission = (permission: Permission) => permissions.includes(permission);
  const hasAnyPermission = (...perms: Permission[]) => perms.some((p) => permissions.includes(p));
  const hasAllPermissions = (...perms: Permission[]) => perms.every((p) => permissions.includes(p));

  return {
    role,
    permissions,
    hasPermission,
    hasAnyPermission,
    hasAllPermissions,
    isLoading,
    isOwner: role === "owner",
    isAdmin: role === "admin" || role === "owner",
    isIntern: role === "intern",
    isClient: role === "client",
  };
};
